project/addressbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
import contacts.views

urlpatterns = patterns('',
    url(r'^$', contacts.views.ListContactView.as_view(),
        name='contacts-list'),

    url(r'^new$', contacts.views.CreateContactView.as_view(),
        name='contacts-new'),

    url(r'^edit/(?P<pk>\d+)/$', contacts.views.UpdateContactView.as_view(),
        name='contacts-edit'),

    url(r'^delete/(?P<pk>\d+)/$', contacts.views.DeleteContactView.as_view(),
        name='contacts-delete'),

    url(r'^(?P<pk>\d+)/$', contacts.views.ContactView.as_view(),
        name='contacts-view',),

    url(r'^edit/(?P<pk>\d+)/addresses$', contacts.views.EditContactAddressView.as_view(),
        name='contacts-edit-addresses',),

    url(r'^search/$', contacts.views.SearchContactView.as_view(),
        name='contacts-search'),

    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/contacts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(
        max_length=255,)
   
    last_name = models.CharField(
        max_length=255,)
   
    email = models.EmailField()
    owner = models.ForeignKey(User)
    
    pic = models.ImageField("Image", upload_to="images/", default='')
    upload_date = models.DateTimeField(auto_now_add=True)
   
    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('contacts-view', kwargs={'pk': self.id})


class AddressType(models.Model):
    type = models.CharField(
        max_length=30,)

    def __str__(self):
        return '%s' % self.type


class Address(models.Model):
    contact = models.ForeignKey(Contact)
    
    address_type = models.ForeignKey(AddressType)

    address = models.CharField(
        max_length=255,)

    city = models.CharField(
        max_length=255,)

    state = models.CharField(
        max_length=2,)

    postal_code = models.CharField(
        max_length=20,)

    class Meta:
        unique_together = ('contact', 'address_type')

project/contacts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import inlineformset_factory


from contacts.models import (
    Contact,
    Address,
)


class ContactForm(forms.ModelForm):
    confirm_email = forms.EmailField(
        label="Confirm email",
        required=True
    )

    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'email', 'pic']

    def __init__(self, *args, **kwargs):
        if kwargs.get('instance'):
            email = kwargs['instance'].email
            kwargs.setdefault('initial', {})['confirm_email'] = email
        super(ContactForm, self).__init__(*args, **kwargs)

    def clean(self):
        if (self.cleaned_data.get('email') !=
                self.cleaned_data.get('confirm_email')):
            raise ValidationError(
                "Email address must match."
            )
        return self.cleaned_data


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['address_type', 'address', 'city', 'state', 'postal_code']

ContactAddressFormSet = inlineformset_factory(
    Contact,
    Address,
)

project/contacts/views.py
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.core.urlresolvers import reverse
from django.core.exceptions import PermissionDenied
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from contacts.models import Contact
from contacts.forms import ContactForm
from contacts.forms import ContactAddressFormSet
from django.http import HttpResponseNotFound


# Create your views here.
class LoggedInMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)


class ContactOwnerMixin(object):
    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        pk = self.kwargs.get(self.pk_url_kwargs, None)
        queryset = queryset.filter(
            pk=pk,
            owner=self.request.user,
        )
        try:
            obj = queryset.get()
        except ObjectDoesNotExist:
            raise PermissionDenied
        return obj


class ListContactView(LoggedInMixin, ContactOwnerMixin, ListView):
    model = Contact
    template_name = 'contact_list.html'
    
    def get_queryset(self):
        return Contact.objects.filter(owner=self.request.user)


class CreateContactView(CreateView):
    model = Contact
    template_name = 'edit_contact.html'
    form_class = ContactForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return super(CreateContactView, self).form_valid(form)

    def get_success_url(self):
        return reverse('contacts-list')

    def get_context_data(self, **kwargs):
        context = super(CreateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-new')
        return context


class UpdateContactView(UpdateView):
    fields = ['first_name', 'last_name', 'email', 'pic']
    model = Contact
    template_name = 'edit_contact.html'
    form_class = ContactForm
    
    def get_success_url(self):
        return reverse('contacts-list')

    def get_context_data(self, **kwargs):
        context = super(UpdateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-edit',
                                    kwargs={'pk': self.get_object().id})
        return context


class DeleteContactView(DeleteView):
    model = Contact
    template_name = 'delete_contact.html'
    
    def get_success_url(self):
        return reverse('contacts-list')


class ContactView(DetailView):
    model = Contact
    template_name = 'contact.html'


class EditContactAddressView(UpdateView):
    model = Contact
    template_name = 'edit_addresses.html'
    form_class = ContactAddressFormSet
    
    def get_success_url(self):
        return self.get_object().get_absolute_url()


class SearchContactView(ListView):
    model = Contact
    template_name = 'contact_list.html'

    def get_queryset(self):
        name = self.request.GET.get('search')
        if name is None:
            return HttpResponseNotFound('Page not found')
        else:
            try:
                obj = self.model.objects.filter(first_name__icontains=name)
            except ObjectDoesNotExist:
                obj = None
            return obj

project/contacts/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
</head>

<body>
	<div>
		{% if user.is_anonymous %}
			<a href="{% url "django.contrib.auth.views.login" %}">login</a>
		{% else %}
			{{ user }}
			<a href="{% url "django.contrib.auth.views.logout" %}">logout</a>
		{% endif %}
	</div>
	<div style="position: fixed; top: 5px; right: 5px;">
        <form action="/search" method="get">
            <input type="text" name="search" value="" />
            <input type="submit" value="search">
        </form>
    </div>
	{% block content %}
	{% endblock %}
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

project/contacts/templates/contact.html
{% extends "base.html" %}

{% block content %}
<h1>{{ contact }}</h1>

<p>Email: {{ contact.email }}</p>

{% if contact.pic %}
<p><img src="{{ MEDIA_URL }}{{ contact.pic }}"></p>
{% endif %}

<ul>
{% for address in contact.address_set.all %}
	<li>
		{{ address.address_type }}<br />
		{{ address.address }}<br />
		{{ address.city }} {{ address.state }}<br />
		{{ address.postal_code }}
	</li>
{% endfor %}
</ul>

<a href="{% url "contacts-list" %}">back</a>
{% endblock %}

project/contacts/templates/contact_list.html
{% extends "base.html" %}

{% block content %}
<h1>Contacts</h1>

<ul>
	{% for contact in object_list %}
		<li class="contact">
			<a href="{{ contact.get_absolute_url }}">{{ contact }}</a>
			(<a href="{% url "contacts-edit" pk=contact.id %}">edit</a>)
			(<a href="{% url "contacts-delete" pk=contact.id %}">delete</a>)
		</li>
	{% endfor %}
</ul>

<a href="{% url "contacts-new" %}">add contact</a>
{% endblock %}

project/contacts/templates/delete_contact.html
{% extends "base.html" %}

{% block content %}
<h1>Delete content</h1>

<p>Are you sure you want to delete the contact {{ contact }}?</p>

<form action="{% url "contacts-delete" pk=contact.id %}" method="post" name="">
	{% csrf_token %}
	
	<input type="submit" value="Yes, delete" /><br />
	<a href="{% url "contacts-list" %}">No, thanks</a>
</form>
{% endblock %}

project/contacts/templates/edit_addresses.html
{% extends "base.html" %}

{% block content %}

<h1>Edit Addresses</h1>

<p>Editing addresses for {{ contact }}</p>

<form action="{% url "contacts-edit-addresses" pk=contact.id %}" method="POST">
	{% csrf_token %}
	{{ form.management_form }}
	{% for address_form in form %}
		<ul>
			{{ address_form.as_ul }}
		</ul>
	{% endfor %}
	<input type="submit" value="Save" />
</form>

{% endblock %}

project/contacts/templates/edit_contact.html
{% extends "base.html" %}

{% block content %}

{% if contact.id %}
<h1>Edit contact</h1>
<a href="{% url "contacts-edit-addresses" pk=contact.id %}">edit addresses</a><br /><br />
{% else %}
<h1>Add contact</h1>
{% endif %}

<form action="{{ action }}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{% if form.non_field_errors %}
	<ul>
		{% for error in form.non_field_errors %}
			<li>{{ error }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	{% for field in form %}
		<div id="{{ field.auto_id }}_container">
			{{ field.help_text }}
			<div>
				{{ field.label_tag }} {{ field }}
			</div>
			<div id="{{ field.auto_id }}_errors">
				{{ field.errors }}
			</div>
		</div>
	{% endfor %}
	<input id="save_contact" type="submit" value="Save" />
</form>

<a href="{% url "contacts-list" %}">back to list</a>
{% endblock %}